# COPYRIGHT Dassault Systemes 2023
#======================================================================
# Imakefile for module DemoMod
#======================================================================
#
#  Jun 2023  Creation: Code generated by TidyCadCompile
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
 ApplicationFrame JS0CORBA CD0FRAME Immersive Palette Commands Ole JS0FM

# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT