set(MYLIBRARY_DIR "${CMAKE_CURRENT_LIST_DIR}")
file(GLOB_RECURSE MYLIBRARY_LIBRARIES "${MYLIBRARY_DIR}/*.lib")

set(MYLIBRARY_FOUND TRUE)
set(MYLIBRARY_INCLUDE_DIR "${MYLIBRARY_DIR}/include")
set(MYLIBRARY_INCLUDE_DIRS ${MYLIBRARY_INCLUDE_DIR})
