// COPYRIGHT Dassault Systemes 2023
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework DemoFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  May 2023  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
AddPrereqComponent("System",Public);
AddPrereqComponent("ApplicationFrame",Public);
AddPrereqComponent("ObjectModelerBase",Public);
AddPrereqComponent("MecModInterfaces",Public);
AddPrereqComponent("ProductStructure",Public);
AddPrereqComponent("DialogEngine",Public);
AddPrereqComponent("Mathematics",Public);
AddPrereqComponent("KnowledgeInterfaces",Public);
// END WIZARD EDITION ZONE
